import './globals.css'

import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'

import ThemeRegistry from '@/theme/ThemeWrapper'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const RootLayout = ({ children }: LayoutProps<'/'>) => (
  <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
    <body>
      <ThemeRegistry>
        <main>{children}</main>
      </ThemeRegistry>
    </body>
  </html>
)

export default RootLayout
